### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by geoglrb** [idris-maps/gis-with-javascript-tutorial#1]
Hello! I'm on the faculty at the University of Washington and I love your work! I'm mulling over how best to start incorporating JS into our GIS teaching and I think that this material could be really helpful. Might you be willing to explicitly license the material in a way that faculty and students could be clearly empowered to use/remix it? Thanks for considering!

**Comment by idris-maps** [comment]
Hello geogirb,
Thank you for your interest and for the reminder. The tutorial is now licensed under CC BY. Hope it works for you
