### ISSUE TITLE
What's the best way to incorporate a database?

### ISSUE THREAD

**Issue by gbertb** [idris-maps/gis-with-javascript-tutorial#2]
Hi, I'm planning on working with lots of data points ~300k+ and use a database to serve out the data  instead of a json file. What's the best approach here?

Would it be wise to use your script found here: https://github.com/idris-maps/geojson-point-tiles -- and use that on the server alongside postGiS and spits out geoJSON, instead?

Thanks!

**Comment by idris-maps** [comment]
Hello gbertb,

Maybe this one solves your problem: https://github.com/mapbox/geojson-vt

Regards,
Idris
